### ISSUE TITLE
What is the shape of the numpy mask

### ISSUE THREAD

**Issue by SurvivorNo1** [Abe404/mask_to_dicom_rtstruct#3]

**Comment by SurvivorNo1** [comment]
Hi! I have some question, could you help me ? 
Is that the numpy mask in your code reffer to  the output of a  segmentation model like Unet? 
And the numpy ndarry shape shoud be (Hight,Width,Deepth) ?

**Comment by Abe404** [comment]
> Hi! I have some question, could you help me ?

I will try :)

> Is that the numpy mask in your code reffer to the output of a segmentation model like Unet?

Yes and the shape is depth, height, width, where depth corresponds to the index of the axial slice.
